// The sector-file status board, straight from the source the Discord board uses.
//
// `data/status.json` in VATSIM-SSA/sectorfile-overview is generated by the
// sector-status workflow from the AIRAC tracker issue + sectors.yml, and is the
// same payload the Discord status embed renders. Reading it here means the site
// and Discord can never disagree about which cycle a sector is on.
//
// Proxied server-side rather than fetched in the browser: the site's CSP limits
// connect-src to 'self' and *.vatssa.com, so a direct raw.githubusercontent.com
// fetch from the client would be blocked.

const DEFAULT_STATUS_URL =
    "https://raw.githubusercontent.com/VATSIM-SSA/sectorfile-overview/main/data/status.json";

// The board is regenerated daily (and on tracker edits), so a 15-minute cache
// keeps the page fresh without hitting GitHub on every visitor.
const REVALIDATE_SECONDS = 900;

export async function GET() {
    try {
        const statusUrl = process.env.SECTOR_STATUS_URL ?? DEFAULT_STATUS_URL;

        const response = await fetch(statusUrl, {
            next: { revalidate: REVALIDATE_SECONDS },
        });

        if (!response.ok) {
            const message = await response.text();

            return new Response(message || "Error fetching sector status.", {
                status: response.status,
            });
        }

        const body = await response.text();

        return new Response(body, {
            status: 200,
            headers: {
                "content-type": "application/json",
            },
        });
    } catch (error) {
        return new Response(
            error instanceof Error ? error.message : "Error fetching sector status.",
            { status: 500 },
        );
    }
}
